-- TCAST staff management and active-session enforcement.
-- Additive only: existing Auth users and business data are preserved.

alter table public.staff_profiles
  add column if not exists username text,
  add column if not exists phone text not null default '',
  add column if not exists must_change_password boolean not null default false,
  add column if not exists last_login_at timestamptz,
  add column if not exists created_by uuid references public.staff_profiles (id) on delete set null,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists disabled_at timestamptz;

-- Give all pre-existing staff a stable username without changing their Auth id.
with username_candidates as (
  select
    id,
    case
      when length(regexp_replace(lower(split_part(email, '@', 1)), '[^a-z0-9._-]', '', 'g')) < 3
        then 'staff-' || left(id::text, 8)
      else regexp_replace(lower(split_part(email, '@', 1)), '[^a-z0-9._-]', '', 'g')
    end as base_username
  from public.staff_profiles
  where username is null or btrim(username) = ''
), ranked_usernames as (
  select
    id,
    base_username,
    row_number() over (partition by base_username order by id) as duplicate_number
  from username_candidates
)
update public.staff_profiles as profile
set username = case
  when ranked.duplicate_number = 1 then left(ranked.base_username, 32)
  else left(ranked.base_username, 27) || '-' || ranked.duplicate_number::text
end
from ranked_usernames as ranked
where profile.id = ranked.id;

alter table public.staff_profiles alter column username set not null;

create unique index if not exists staff_profiles_username_lower_uidx
  on public.staff_profiles (lower(username));
create unique index if not exists staff_profiles_email_lower_uidx
  on public.staff_profiles (lower(email));
create index if not exists staff_profiles_created_by_idx
  on public.staff_profiles (created_by);
create index if not exists staff_profiles_active_role_idx
  on public.staff_profiles (active, role);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'staff_profiles_username_format_check'
      and conrelid = 'public.staff_profiles'::regclass
  ) then
    alter table public.staff_profiles
      add constraint staff_profiles_username_format_check
      check (username ~ '^[a-z0-9][a-z0-9._-]{2,31}$');
  end if;
end $$;

create table if not exists public.staff_management_audit (
  id bigint generated by default as identity primary key,
  action text not null check (action in (
    'STAFF_CREATED', 'STAFF_UPDATED', 'PASSWORD_RESET',
    'ROLE_CHANGED', 'ACCOUNT_DISABLED', 'ACCOUNT_ENABLED',
    'PASSWORD_CHANGED'
  )),
  target_staff_id uuid references public.staff_profiles (id) on delete set null,
  performed_by uuid references public.staff_profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists staff_management_audit_target_idx
  on public.staff_management_audit (target_staff_id, created_at desc);
create index if not exists staff_management_audit_actor_idx
  on public.staff_management_audit (performed_by, created_at desc);

alter table public.staff_management_audit enable row level security;
grant select on public.staff_management_audit to authenticated;
grant usage, select on sequence public.staff_management_audit_id_seq to authenticated;

-- SECURITY DEFINER avoids recursive staff_profiles RLS checks. The calling
-- identity is always derived from auth.uid(), never from browser input.
create or replace function public.is_active_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.staff_profiles
    where id = (select auth.uid())
      and active
      and not must_change_password
  );
$$;

create or replace function public.is_staff_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.staff_profiles
    where id = (select auth.uid())
      and active
      and not must_change_password
      and role = 'Admin'
  );
$$;

revoke all on function public.is_active_staff() from public, anon;
revoke all on function public.is_staff_admin() from public, anon;
grant execute on function public.is_active_staff() to authenticated;
grant execute on function public.is_staff_admin() to authenticated;

create or replace function public.staff_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select role
  from public.staff_profiles
  where id = (select auth.uid())
    and active
    and not must_change_password
$$;

revoke all on function public.staff_role() from public, anon;
grant execute on function public.staff_role() to authenticated;

-- Restrictive policies are ANDed with existing role/module policies. This
-- closes every direct Data API path for disabled staff without changing the
-- public exact-tracking RPC.
do $$
declare
  protected_table text;
begin
  foreach protected_table in array array[
    'customers', 'packing_lists', 'shipments', 'payment_records', 'expenses',
    'company_settings', 'shipping_rates', 'exchange_rates', 'shipment_items',
    'rate_change_audit', 'packing_boxes', 'packing_list_items'
  ] loop
    execute format('drop policy if exists "active staff access gate" on public.%I', protected_table);
    execute format(
      'create policy "active staff access gate" on public.%I as restrictive for all to authenticated using ((select public.is_active_staff())) with check ((select public.is_active_staff()))',
      protected_table
    );
  end loop;
end $$;

drop policy if exists "staff can read profiles" on public.staff_profiles;
drop policy if exists "staff can update own profile" on public.staff_profiles;
drop policy if exists "admins can update any profile" on public.staff_profiles;
drop policy if exists "admins can delete profiles" on public.staff_profiles;

create policy "staff can read own profile" on public.staff_profiles
  for select to authenticated
  using (id = (select auth.uid()));
create policy "admins can read staff profiles" on public.staff_profiles
  for select to authenticated
  using ((select public.is_staff_admin()));
create policy "admins can update staff profiles" on public.staff_profiles
  for update to authenticated
  using ((select public.is_staff_admin()))
  with check ((select public.is_staff_admin()));

drop policy if exists "admins can read staff audit" on public.staff_management_audit;
create policy "admins can read staff audit" on public.staff_management_audit
  for select to authenticated
  using ((select public.is_staff_admin()));

-- Direct profile updates are deliberately narrow. Auth email, role, status,
-- username and password changes go through the authenticated Edge Functions.
create or replace function public.staff_profiles_guard_self_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) = old.id and not public.is_staff_admin() then
    if new.role is distinct from old.role
      or new.active is distinct from old.active
      or new.username is distinct from old.username
      or new.email is distinct from old.email
      or new.created_by is distinct from old.created_by
      or new.must_change_password is distinct from old.must_change_password then
      raise exception 'Privileged staff fields can only be changed through the secure staff service.';
    end if;
  end if;
  new.updated_at = now();
  return new;
end;
$$;

-- Public signup stays outside this migration. The application exposes no
-- registration path; only an authenticated Admin Edge Function creates users.
